version: "3.9"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
      - cluster.name=docker-cluster
    ports:
      - "${ES_PORT_HTTP}:9200"
      - "${ES_PORT_TRANSPORT}:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - backend_cache_network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\\\"status\":\"yellow\"'"]
      interval: 10s
      timeout: 10s
      retries: 10

  cache_app:
    build: .
    container_name: cache_service
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTIC_POOL_SIZE=${ELASTIC_POOL_SIZE}
      - ELASTIC_POOL_TIMEOUT=${ELASTIC_POOL_TIMEOUT}
      - ELASTIC_INDEX_NAME=${ELASTIC_INDEX_NAME}
      - ELASTIC_INDEX_ALIAS=${ELASTIC_INDEX_ALIAS}
      - RACK_ENV=production
    ports:
      - "${CACHE_APP_PORT}:9292"
    networks:
      - backend_cache_network

    depends_on:
      es:
        condition: service_healthy
    volumes:
      - .:/app
    command: sh -c "sleep 5 && bundle exec puma -C config/puma.rb"

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - "${KIBANA_PORT}:5601"
    networks:
      - backend_cache_network
    depends_on:
      es:
        condition: service_healthy

volumes:
  esdata:

networks:
  backend_cache_network:
    external: true